#!/usr/bin/env python3
# Embed a binary file as a C byte array header. SPDX-License-Identifier: MIT
# Usage: elf2h.py <infile> <symbol> <out.h>
import sys
inf, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
data = open(inf, "rb").read()
arr = ",".join("0x%02x" % b for b in data)
guard = sym.upper() + "_H"
open(out, "w").write(
    "/* Generated by tools/elf2h.py from %s. Do not edit by hand. */\n"
    "#ifndef %s\n#define %s\n#include <stddef.h>\n#include <stdint.h>\n"
    "static const uint8_t %s[] = {%s};\n"
    "static const size_t  %s_len = %d;\n#endif\n"
    % (inf, guard, guard, sym, arr, sym, len(data)))
sys.stderr.write("[elf2h] %s -> %s (%d bytes)\n" % (inf, out, len(data)))
