#!/usr/bin/env python3
# Build a minimal SIGNED test ELF (with .note.secos QSEC+QSIG) and emit it as a
# C header for the kernel signature-verify self-test. SPDX-License-Identifier: MIT
import sys, os, struct
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from secos_signlib import DEV_SEED, build_note_blob, find_qsig_sig_offset, compute_digest

USER_CODE_BASE = 0x100000000
OUT = "crypto/signed_test_elf.h"

def build_elf():
    code = bytes([0x48,0xC7,0xC0,0x01,0x00,0x00,0x00, 0xCD,0x80])  # mov rax,1; int 0x80 (SYS_EXIT)
    manifest = struct.pack("<IIQQ", 1, 0, 0, 0)                    # version, flags, max_mem, entry
    note = build_note_blob(manifest, key_id=0)

    CODE_OFF, NOTE_OFF = 0x100, 0x200
    data = bytearray(NOTE_OFF + len(note))
    # ELF64 header
    data[0:7] = bytes([0x7f, ord('E'), ord('L'), ord('F'), 2, 1, 1])
    struct.pack_into("<H", data, 16, 2)            # ET_EXEC
    struct.pack_into("<H", data, 18, 0x3E)         # EM_X86_64
    struct.pack_into("<I", data, 20, 1)            # EV_CURRENT
    struct.pack_into("<Q", data, 24, USER_CODE_BASE)  # e_entry
    struct.pack_into("<Q", data, 32, 64)           # e_phoff
    struct.pack_into("<H", data, 52, 64)           # e_ehsize
    struct.pack_into("<H", data, 54, 56)           # e_phentsize
    struct.pack_into("<H", data, 56, 2)            # e_phnum
    # phdr[0]: PT_LOAD code (R|X)
    p = 64
    struct.pack_into("<I", data, p+0, 1)           # PT_LOAD
    struct.pack_into("<I", data, p+4, 0x5)         # PF_R|PF_X
    struct.pack_into("<Q", data, p+8, CODE_OFF)    # p_offset
    struct.pack_into("<Q", data, p+16, USER_CODE_BASE)
    struct.pack_into("<Q", data, p+24, USER_CODE_BASE)
    struct.pack_into("<Q", data, p+32, len(code))  # p_filesz
    struct.pack_into("<Q", data, p+40, len(code))  # p_memsz
    struct.pack_into("<Q", data, p+48, 0x1000)     # p_align
    # phdr[1]: PT_NOTE
    p = 64 + 56
    struct.pack_into("<I", data, p+0, 4)           # PT_NOTE
    struct.pack_into("<Q", data, p+8, NOTE_OFF)    # p_offset
    struct.pack_into("<Q", data, p+32, len(note))  # p_filesz
    data[CODE_OFF:CODE_OFF+len(code)] = code
    data[NOTE_OFF:NOTE_OFF+len(note)] = note
    return bytearray(data)

def main():
    data = build_elf()
    off = find_qsig_sig_offset(data)
    assert off is not None, "QSIG note not found in generated ELF"
    for k in range(64): data[off+k] = 0
    sig = Ed25519PrivateKey.from_private_bytes(DEV_SEED).sign(compute_digest(data, off))
    data[off:off+64] = sig

    def carr(b): return ",".join("0x%02x" % x for x in b)
    hdr = ("/* Generated by tools/gen_signed_test.py — a minimal DEV-signed ELF\n"
           " * for the kernel signature-verify self-test. Do not edit by hand. */\n"
           "#ifndef SECOS_SIGNED_TEST_ELF_H\n#define SECOS_SIGNED_TEST_ELF_H\n#include <stddef.h>\n#include <stdint.h>\n"
           "static const uint8_t signed_test_elf[] = {%s};\n"
           "static const size_t  signed_test_elf_len = %d;\n#endif\n") % (carr(data), len(data))
    open(OUT, "w").write(hdr)
    sys.stderr.write("[gen] wrote %s (%d bytes, sig@%d)\n" % (OUT, len(data), off))

if __name__ == "__main__":
    main()
